package entservice

import (
	"context"
	"fmt"

	"entgo.io/ent/entc/gen"
	"entgo.io/ent/schema/field"
	"github.com/dave/jennifer/jen"
	"github.com/syralon/coconutc/internal/tools/text"
)

func EntityBuilder(pkg string, withEdge bool) BuildFunc {
	return func(ctx context.Context, node *gen.Type, opts *BuildOptions) (*jen.File, error) {
		file := jen.NewFile(pkg)
		file.HeaderComment("Code generated by coconutc. DO NOT EDIT.")
		file.HeaderComment("https://github.com/syralon/coconutc")
		file.ImportAlias(opts.ProtoPackage, "pb")

		file.Type().Id(node.Name).Struct(
			jen.Op("*").Qual(opts.EntPackage, node.Name),
		)
		toProtoFunc(file, node, opts, withEdge)
		return file, nil
	}
}

func toProtoFunc(file *jen.File, node *gen.Type, opts *BuildOptions, withEdge bool) {
	var fields []jen.Code
	fields = append(
		fields,
		jen.Id("Id").Op(":").Add(entID(node, jen.Id("data").Dot("ID"))).Op(","),
	)
	for _, fi := range node.Fields {
		var v *jen.Statement
		if fi.Type.Type == field.TypeTime {
			v = jen.Qual(pkgTimestamppb, "New").
				Call(jen.Id("data").Dot(text.EntPascal(fi.Name)))
		} else {
			v = jen.Id("data").Dot(text.EntPascal(fi.Name))
		}
		v = unwrap(fi, v)
		fields = append(fields, jen.Id(text.ProtoPascal(fi.Name)).Op(":").Add(v).Op(","))
	}

	if withEdge {
		for _, fi := range node.Edges {
			var v *jen.Statement
			if fi.Unique {
				v = jen.Id(fmt.Sprintf("%sToProto", fi.Type.Name)).Call(jen.Id("data").Dot("Edges").Dot(text.EntPascal(fi.Name)))
			} else {
				v = jen.Qual(pkgXSlices, "Trans").Call(
					jen.Id("data").Dot("Edges").Dot(text.EntPascal(fi.Name)),
					jen.Id(fmt.Sprintf("%sToProto", fi.Type.Name)),
				)
			}
			fields = append(fields, jen.Id(text.ProtoPascal(fi.Name)).Op(":").Add(v).Op(","))
		}
	}

	file.Func().
		Params(jen.Id("data").Op("*").Id(node.Name)).Id("ToProto").
		Params().Op("*").Qual(opts.ProtoPackage, text.ProtoPascal(node.Name)).
		Block(
			jen.If(jen.Id("data").Op("==").Nil()).Block(jen.Return(jen.Nil())),
			jen.Return(
				jen.Op("&").Qual(opts.ProtoPackage, text.ProtoPascal(node.Name)).Block(fields...),
			),
		).
		Line()

	file.Func().
		Id(fmt.Sprintf("%sToProto", node.Name)).
		Params(jen.Id("data").Op("*").Id(node.Name)).
		Op("*").Qual(opts.ProtoPackage, text.ProtoPascal(node.Name)).
		Block(
			jen.Id("data").Dot("ToProto").Call(),
		)
}
