// generate unit test for repository

package entservice

import (
	"context"
	"fmt"
	"math/rand"
	"path"

	"entgo.io/ent/entc/gen"
	"entgo.io/ent/schema/field"
	"github.com/dave/jennifer/jen"
	"github.com/iancoleman/strcase"
	"github.com/syralon/coconutc/internal/tools/text"
	"github.com/syralon/coconutc/pkg/annotation/entproto"
)

func RepositoryUnitTestBuilder(pkgName, entityPackage, txPackage string) BuildFunc {
	return func(ctx context.Context, node *gen.Type, opts *BuildOptions) (*jen.File, error) {
		file := jen.NewFile(pkgName)
		file.HeaderComment("Code generated by coconutc. DO NOT EDIT.")
		file.HeaderComment("https://github.com/syralon/coconutc")
		file.HeaderComment("ent." + node.Name)
		file.ImportAlias(opts.ProtoPackage, "pb")
		file.Anon(pkgSyralonSqlite)
		b := &repositoryUnitTestBuilder{
			BuildOptions: opts,
			builder: builder{
				name: fmt.Sprintf("%sRepository", node.Name),
				node: node,
				file: file,
			},
			enttestPackage: path.Join(opts.EntPackage, "enttest"),
			txPackage:      txPackage,
			entityPackage:  entityPackage, // TODO
		}
		err := b.build(ctx)
		if err != nil {
			return nil, err
		}
		return file, nil
	}
}

type repositoryUnitTestBuilder struct {
	*BuildOptions
	builder

	txPackage      string
	entityPackage  string
	enttestPackage string
}

func (b *repositoryUnitTestBuilder) build(ctx context.Context) error {
	b.file.Add(segments(
		b.getAssertStruct(),
		b.get(),

		b.listAssertStruct(),
		b.list(),

		b.createAssertStruct(),
		b.create(),

		b.updateAssertStruct(),
		b.update(),

		b.deleteAssertStruct(),
		b.delete(),

		b.setAssertStruct(),
		b.set(),

		b.integration(),
		b.errorHandling(),
	))
	return nil
}

func (b *repositoryUnitTestBuilder) head() jen.Code {
	return segments(
		// client := enttest.MemoryClient(t)
		// defer client.Close()
		// repo := NewExampleRepository(tx.NewRepository(client))
		// ctx := context.Background()
		define("client").Qual(b.enttestPackage, "MemoryClient").Call(jen.Id("t")),
		jen.Defer().Id("client").Dot("Close").Call(),
		jen.Line(),
		define("repo").Id("New"+b.name).Call(jen.Qual(b.txPackage, "NewRepository").Call(jen.Id("client"))),
		define("ctx").Qual(pkgContext, "Background").Call(),
	)
}

func (b *repositoryUnitTestBuilder) get() jen.Code {
	return jen.Func().Id(fmt.Sprintf("Test%s_Get", b.name)).Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).
		Block(
			b.head(),
			jen.Line(),
			b.getBody(),
		)
}

func (b *repositoryUnitTestBuilder) list() jen.Code {
	return jen.Func().Id(fmt.Sprintf("Test%s_List", b.name)).Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).
		Block(
			b.head(),
			jen.Line(),
			b.listBody(),
		)
}

func (b *repositoryUnitTestBuilder) create() jen.Code {
	return jen.Func().Id(fmt.Sprintf("Test%s_Create", b.name)).Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).
		Block(
			b.head(),
			jen.Line(),
			b.createBody(),
		)

}

func (b *repositoryUnitTestBuilder) update() jen.Code {
	return jen.Func().Id(fmt.Sprintf("Test%s_Update", b.name)).Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).
		Block(
			b.head(),
			jen.Line(),
			b.updateBody(),
		)
}

func (b *repositoryUnitTestBuilder) delete() jen.Code {
	return jen.Func().Id(fmt.Sprintf("Test%s_Delete", b.name)).Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).
		Block(
			b.head(),
			jen.Line(),
			jen.Comment("Create test data"),

			// create := &pb.ExampleCreate{}
			// created, err := repo.Create(ctx, create)
			// require.NoError(t ,err)
			// require.NotNil(t, created)
			define("create").Op("&").Qual(b.ProtoPackage, b.node.Name+"Create").Add(b.mockData()),
			define("created", "err").Id("repo").Dot("Create").Call(jen.Id("ctx"), jen.Id("create")),
			jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Id("err")),
			jen.Qual(pkgTestifyRequire, "NotNil").Call(jen.Id("t"), jen.Id("created")),
			jen.Line(),

			// tests := []ExampleDeleteAssert{}
			define("tests").Op("[]").Id(fmt.Sprintf("%sDeleteAssert", b.node.Name)).Block(
				jen.Block(
					jen.Id("name").Op(":").Lit("successful delete").Op(","),
					jen.Id("id").Op(":").Id("created").Dot("ID").Op(","),
					jen.Id("wantError").Op(":").False().Op(","),
				).Op(","),
				jen.Block(
					jen.Id("name").Op(":").Lit("delete non-existent").Op(","),
					jen.Id("id").Op(":").Lit(99999).Op(","),
					jen.Id("wantError").Op(":").True().Op(","),
				).Op(","),
				jen.Block(
					jen.Id("name").Op(":").Lit("delete already deleted").Op(","),
					jen.Id("id").Op(":").Id("created").Dot("ID").Op(",").Comment("// Already deleted above"),
					jen.Id("wantError").Op(":").True().Op(","),
				).Op(","),
				jen.Block(
					jen.Id("name").Op(":").Lit("delete with invalid id").Op(","),
					jen.Id("id").Op(":").Lit(-1).Op(","),
					jen.Id("wantError").Op(":").True().Op(","),
				).Op(","),
			),

			// for _, tt := range tests {}
			jen.For(jen.Id("_").Op(",").Id("tt").Op(":=").Range().Id("tests")).Block(
				// t.Run(tt.name, func(t *testing.T)) {}
				jen.Id("t").Dot("Run").Call(
					jen.Id("tt").Dot("name"),
					jen.Func().Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).Block(
						define("err").Id("repo").Dot("Delete").Call(jen.Id("ctx"), jen.Id("tt").Dot("id")),
						jen.If(jen.Id("tt").Dot("wantError")).
							Block(jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err())).
							Else().
							Block(
								jen.Qual(pkgTestifyAssert, "NoError").Call(jen.Id("t"), jen.Err()),
								jen.Comment(" Verify deletion"),
								define("_", "err").Id("repo").Dot("Get").Call(jen.Id("ctx"), jen.Id("tt").Dot("id")),
								jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err()).Comment("Should not find the record"),
							),
					),
				),
			),
		)
}

func (b *repositoryUnitTestBuilder) set() jen.Code {
	var codes []jen.Code
	for _, v := range b.node.Fields {
		if v.Name == "created_at" || v.Name == "updated_at" {
			continue
		}
		if v.Immutable {
			continue
		}
		fieldOpts, err := entproto.GetFieldOptions(v.Annotations)
		if err != nil {
			panic(err)
		}
		if fieldOpts.Immutable || !fieldOpts.Settable {
			continue
		}

		var t jen.Code
		if fieldOpts.ProtoEnum {
			t = jen.Qual(b.ProtoPackage, strcase.ToScreamingSnake(fmt.Sprintf("%s_%s", b.node.Name, v.Name)))
		} else {
			t = fieldProtoType(v.Type.Type)
		}
		fn := jen.Func().Id(fmt.Sprintf("Test%s_Set%s", b.name, text.EntPascal(v.Name))).Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).
			Block(
				b.head(),
				jen.Line(),
				jen.Comment("Create test data"),

				// create := &pb.ExampleCreate{}
				// created, err := repo.Create(ctx, create)
				// require.NoError(t ,err)
				// require.NotNil(t, created)
				define("create").Op("&").Qual(b.ProtoPackage, b.node.Name+"Create").Add(b.mockData()),
				define("created", "err").Id("repo").Dot("Create").Call(jen.Id("ctx"), jen.Id("create")),
				jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Id("err")),
				jen.Qual(pkgTestifyRequire, "NotNil").Call(jen.Id("t"), jen.Id("created")),
				jen.Line(),
				// tests := []ExampleSetAssert{}
				define("tests").Op("[]").Id(fmt.Sprintf("%sSetAssert", b.node.Name)).Index(t).Block(
					jen.Block(
						jen.Id("name").Op(":").Lit("successful set").Op(","),
						jen.Id("id").Op(":").Id("created").Dot("ID").Op(","),
						jen.Id("value").Op(":").Add(b.mockValue(v, &fieldOpts)).Op(","),
						jen.Id("wantError").Op(":").False().Op(","),
					).Op(","),
					jen.Block(
						jen.Id("name").Op(":").Lit("set "+v.Name+" for non-existent").Op(","),
						jen.Id("id").Op(":").Lit(99999).Op(","),
						jen.Id("value").Op(":").Add(b.mockValue(v, &fieldOpts)).Op(","),
						jen.Id("wantError").Op(":").False().Op(",").Comment("Update operation might not error for non-existent"),
					).Op(","),
					jen.Block(
						jen.Id("name").Op(":").Lit("set "+v.Name+" with invalid id").Op(","),
						jen.Id("id").Op(":").Lit(-1).Op(","),
						jen.Id("value").Op(":").Add(b.mockValue(v, &fieldOpts)).Op(","),
						jen.Id("wantError").Op(":").False().Op(",").Comment("Update operation might not error for invalid id"),
					).Op(","),
				),
				// for _, tt := range tests {}
				jen.For(jen.Id("_").Op(",").Id("tt").Op(":=").Range().Id("tests")).Block(
					// t.Run(tt.name, func(t *testing.T)) {}
					jen.Id("t").Dot("Run").Call(
						jen.Id("tt").Dot("name"),
						jen.Func().Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).Block(
							define("err").Id("repo").Dot("Set"+text.EntPascal(v.Name)).Call(jen.Id("ctx"), jen.Id("tt").Dot("id"), jen.Id("tt").Dot("value")),
							jen.If(jen.Id("tt").Dot("wantError")).
								Block(jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err())).
								Else().
								Block(
									jen.Qual(pkgTestifyAssert, "NoError").Call(jen.Id("t"), jen.Err()),
									jen.Comment(" Verify "+v.Name+" change if ID exists"),
									jen.If(jen.Id("tt").Dot("id").Op("==").Id("created").Dot("ID")).Block(
										define("updated", "err").Id("repo").Dot("Get").Call(jen.Id("ctx"), jen.Id("tt").Dot("id")),
										jen.If(jen.Err().Op("==").Nil()).Block(
											jen.Comment(" Only check if record still exists"),
											jen.Qual(pkgTestifyAssert, "Equal").Call(
												jen.Id("t"),
												entType(v.Type.Type, jen.Id("tt").Dot("value"), &fieldOpts),
												jen.Id("updated").Dot(text.EntPascal(v.Name)),
											),
										),
									),
								),
						),
					),
				),
			).Line()
		codes = append(codes, fn)
	}
	return segments(codes...)
}

func (b *repositoryUnitTestBuilder) integration() jen.Code {
	sets := make([]jen.Code, 0)
	for _, v := range b.node.Fields {
		if v.Name == "created_at" || v.Name == "updated_at" {
			continue
		}
		if v.Immutable {
			continue
		}
		fieldOpts, err := entproto.GetFieldOptions(v.Annotations)
		if err != nil {
			panic(err)
		}
		if fieldOpts.Immutable || !fieldOpts.Settable {
			continue
		}
		//val := b.mockValue(v, &fieldOpts)

		updatedValName := strcase.ToLowerCamel(v.Name + "Updated")
		sets = append(
			sets,
			segments(
				jen.Comment(" Set "+v.Name),
				define(strcase.ToLowerCamel(v.Name+"Value")).Add(b.mockValue(v, &fieldOpts)),
				assign("err").Id("repo").Dot("Set"+text.EntPascal(v.Name)).Call(jen.Id("ctx"), jen.Id("created").Dot("ID"), jen.Id(strcase.ToLowerCamel(v.Name+"Value"))),
				jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Err()),
				jen.Comment(" Verify "+v.Name+" change"),
				define(updatedValName, "err").Id("repo").Dot("Get").Call(jen.Id("ctx"), jen.Id("created").Dot("ID")),
				jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Err()),
				jen.Qual(pkgTestifyAssert, "Equal").Call(
					jen.Id("t"),
					entType(v.Type.Type, jen.Id(strcase.ToLowerCamel(v.Name+"Value")), &fieldOpts),
					jen.Id(updatedValName).Dot(text.EntPascal(v.Name)),
				),
			),
			jen.Line(),
		)
	}

	return jen.Func().Id(fmt.Sprintf("Test%s_Integration", b.name)).Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).
		Block(
			b.head(),
			jen.Line(),

			jen.Id("t").Dot("Run").Call(
				jen.Lit("complete CRUD lifecycle"),
				jen.Func().Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).Block(
					jen.Comment(" Create"),
					define("create").Op("&").Qual(b.ProtoPackage, b.node.Name+"Create").Add(b.mockData()),
					jen.Line(),

					define("created", "err").Id("repo").Dot("Create").Call(jen.Id("ctx"), jen.Id("create")),
					jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Err()),
					jen.Qual(pkgTestifyRequire, "NotNil").Call(jen.Id("t"), jen.Id("created")),
					jen.Line(),

					jen.Comment(" Read"),
					define("retrieved", "err").Id("repo").Dot("Get").Call(jen.Id("ctx"), jen.Id("created").Dot("ID")),
					jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Err()),
					jen.Qual(pkgTestifyRequire, "NotNil").Call(jen.Id("t"), jen.Id("retrieved")),
					jen.Qual(pkgTestifyAssert, "Equal").Call(jen.Id("t"), jen.Id("created").Dot("ID"), jen.Id("retrieved").Dot("ID")),
					jen.Line(),

					jen.Comment(" List"),
					define("list", "_", "err").Id("repo").Dot("List").Call(jen.Id("ctx"), jen.Op("&").Qual(b.ProtoPackage, b.node.Name+"Options").Block(), jen.Nil()),
					jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Err()),
					jen.Qual(pkgTestifyAssert, "Len").Call(jen.Id("t"), jen.Id("list"), jen.Lit(1)),
					jen.Line(),

					segments(sets...),
					jen.Line(),

					jen.Comment(" Delete"),
					assign("err").Id("repo").Dot("Delete").Call(jen.Id("ctx"), jen.Id("created").Dot("ID")),
					jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Err()),
					jen.Comment(" Verify deletion"),
					assign("_", "err").Id("repo").Dot("Get").Call(jen.Id("ctx"), jen.Id("created").Dot("ID")),
					jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err()),
					jen.Qual(pkgTestifyAssert, "Equal").Call(jen.Id("t"), jen.Qual(b.EntPackage, "IsNotFound").Call(jen.Err()), jen.True()),
					jen.Line(),
				),
			),
		).Line()
}

func (b *repositoryUnitTestBuilder) errorHandling() jen.Code {
	return jen.Func().Id(fmt.Sprintf("Test%s_ErrorHandling", b.name)).Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).
		Block(
			b.head(),
			jen.Line(),
			jen.Id("t").Dot("Run").Call(jen.Lit("context cancellation"), jen.Func().Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).Block(
				define("cancelledCtx", "cancel").Qual(pkgContext, "WithCancel").Call(jen.Id("ctx")),
				jen.Id("cancel").Call().Comment(" Cancel immediately"),
				define("create").Op("&").Qual(b.ProtoPackage, b.node.Name+"Create").Add(b.mockData()),
				define("_", "err").Id("repo").Dot("Create").Call(jen.Id("cancelledCtx"), jen.Id("create")),
				jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err()),
				jen.Qual(pkgTestifyAssert, "ErrorIs").Call(jen.Id("t"), jen.Err(), jen.Qual(pkgContext, "Canceled")),
			)),
			jen.Line(),
			jen.Id("t").Dot("Run").Call(jen.Lit("context cancellation"), jen.Func().Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).Block(
				jen.Comment(" Test with nil create"),
				define("_", "err").Id("repo").Dot("Create").Call(jen.Id("ctx"), jen.Nil()),
				jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err()),
				jen.Line(),

				jen.Comment(" Test with nil update"),
				assign("err").Id("repo").Dot("Update").Call(jen.Id("ctx"), jen.Lit(1), jen.Nil()),
				jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err()),
				jen.Line(),

				jen.Comment(" Test with nil options"),

				define("list", "_", "err").Id("repo").Dot("List").Call(jen.Id("ctx"), jen.Nil(), jen.Nil()),
				jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err()),
				jen.Qual(pkgTestifyAssert, "Nil").Call(jen.Id("t"), jen.Id("list")),
			)),
		)
}

func (b *repositoryUnitTestBuilder) getBody() jen.Code {
	return segments(
		jen.Comment("Create test data"),

		// create := &pb.ExampleCreate{}
		// created, err := repo.Create(ctx, create)
		// require.NoError(t ,err)
		// require.NotNil(t, created)
		define("create").Op("&").Qual(b.ProtoPackage, b.node.Name+"Create").Add(b.mockData()),
		define("created", "err").Id("repo").Dot("Create").Call(jen.Id("ctx"), jen.Id("create")),
		jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Id("err")),
		jen.Qual(pkgTestifyRequire, "NotNil").Call(jen.Id("t"), jen.Id("created")),

		// tests := []ExampleGetAssert{}
		define("tests").Op("[]").Id(fmt.Sprintf("%sGetAssert", b.node.Name)).Block(
			jen.Block(
				jen.Id("name").Op(":").Lit("successful get").Op(","),
				jen.Id("id").Op(":").Id("created").Dot("ID").Op(","),
				jen.Id("want").Op(":").Id("created").Op(","),
				jen.Id("wantError").Op(":").False().Op(","),
			).Op(","),
			jen.Block(
				jen.Id("name").Op(":").Lit("not found").Op(","),
				jen.Id("id").Op(":").Lit(99999).Op(","),
				jen.Id("want").Op(":").Nil().Op(","),
				jen.Id("wantError").Op(":").True().Op(","),
			).Op(","),
			jen.Block(
				jen.Id("name").Op(":").Lit("invalid id").Op(","),
				jen.Id("id").Op(":").Lit(-1).Op(","),
				jen.Id("want").Op(":").Nil().Op(","),
				jen.Id("wantError").Op(":").True().Op(","),
			).Op(","),
		),

		// for _, tt := range tests {}
		jen.For(jen.Id("_").Op(",").Id("tt").Op(":=").Range().Id("tests")).Block(
			// t.Run(tt.name, func(t *testing.T)) {}
			jen.Id("t").Dot("Run").Call(
				jen.Id("tt").Dot("name"),
				jen.Func().Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).Block(
					// got, err := repo.Get(ctx, tt.id)
					define("got", "err").Id("repo").Dot("Get").Call(jen.Id("ctx"), jen.Id("tt").Dot("id")),
					jen.If(jen.Id("tt").Dot("wantError")).
						Block(
							jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err()),
							jen.Qual(pkgTestifyAssert, "Nil").Call(jen.Id("t"), jen.Id("got")),
						).
						Else().
						Block(
							jen.Qual(pkgTestifyAssert, "NoError").Call(jen.Id("t"), jen.Err()),
							jen.Qual(pkgTestifyAssert, "NotNil").Call(jen.Id("t"), jen.Id("got")),
							jen.Add(b.assertEqualGetFields()),
						),
				),
			),
		),
	)
}

func (b *repositoryUnitTestBuilder) listBody() jen.Code {
	return segments(
		jen.Comment("Create test data"),
		// testData := []*pb.ExampleCreate{}
		define("testData").Op("[]").Op("*").Qual(b.ProtoPackage, b.node.Name+"Create").Block(b.mockData().Op(","), b.mockData().Op(","), b.mockData().Op(",")),
		// for _, create := range testData {}
		jen.For(jen.Id("_").Op(",").Id("create").Op(":=").Range().Id("testData")).Block(
			define("_", "err").Id("repo").Dot("Create").Call(jen.Id("ctx"), jen.Id("create")),
			jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Err()),
		),
		jen.Line(),
		// tests := []ExampleListAssert{}
		define("tests").Op("[]").Id(fmt.Sprintf("%sListAssert", b.node.Name)).Block(b.listTestCases()),
		// for _, tt := range tests {}
		jen.For(jen.Id("_").Op(",").Id("tt").Op(":=").Range().Id("tests")).Block(
			jen.Id("t").Dot("Run").Call(jen.Id("tt").Dot("name"), jen.Func().Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).Block(
				define("got", "paginator", "err").Id("repo").Dot("List").Call(jen.Id("ctx"), jen.Id("tt").Dot("options"), jen.Id("tt").Dot("paginator")),
				jen.If(jen.Id("tt").Dot("wantError")).
					Block(jen.Qual(pkgTestifyAssert, "NoError").Call(jen.Id("t"), jen.Id("err"))).
					Else().
					Block(
						jen.Qual(pkgTestifyAssert, "NoError").Call(jen.Id("t"), jen.Id("err")),
						jen.Qual(pkgTestifyAssert, "Equal").Call(jen.Id("t"), jen.Id("tt").Dot("wantCount"), jen.Len(jen.Id("got"))),
						jen.If(jen.Id("tt").Dot("paginator").Op("!=").Nil()).Block(
							jen.Qual(pkgTestifyAssert, "NotNil").Call(jen.Id("t"), jen.Id("paginator")),
							jen.Qual(pkgTestifyAssert, "Equal").Call(jen.Id("t"), jen.Int64().Call(jen.Lit(3)), jen.Id("paginator").Dot("Total")),
						),
					),
			)),
		),
	)
}

func (b *repositoryUnitTestBuilder) createBody() jen.Code {
	return segments(
		define("tests").Op("[]").Id(fmt.Sprintf("%sCreateAssert", b.node.Name)).Block(
			jen.Block(
				jen.Id("name").Op(":").Lit("successful create with all fields").Op(","),
				jen.Id("create").Op(":").Op("&").Qual(b.ProtoPackage, b.node.Name+"Create").Add(b.mockData()).Op(","),
				jen.Id("wantError").Op(":").False().Op(","),
			).Op(","),
			jen.Block(
				jen.Id("name").Op(":").Lit("successful create with empty fields").Op(","),
				jen.Id("create").Op(":").Op("&").Qual(b.ProtoPackage, b.node.Name+"Create").Block().Op(","),
				jen.Id("wantError").Op(":").False().Op(","),
			).Op(","),
		),

		// for _, tt := range tests {}
		jen.For(jen.Id("_").Op(",").Id("tt").Op(":=").Range().Id("tests")).Block(
			// t.Run(tt.name, func(t *testing.T)) {}
			jen.Id("t").Dot("Run").Call(
				jen.Id("tt").Dot("name"),
				jen.Func().Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).Block(
					// got, err := repo.Get(ctx, tt.id)
					define("got", "err").Id("repo").Dot("Create").Call(jen.Id("ctx"), jen.Id("tt").Dot("create")),
					// if tt.wantError {} else {}
					jen.If(jen.Id("tt").Dot("wantError")).
						Block(
							jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err()),
							jen.Qual(pkgTestifyAssert, "Nil").Call(jen.Id("t"), jen.Id("got")),
						).
						Else().
						Block(
							jen.Qual(pkgTestifyAssert, "NoError").Call(jen.Id("t"), jen.Err()),
							jen.Qual(pkgTestifyAssert, "NotNil").Call(jen.Id("t"), jen.Id("got")),
							jen.Add(b.assertEqualCreateFields()),
							jen.Qual(pkgTestifyAssert, "NotZero").Call(jen.Id("t"), jen.Id("got").Dot("CreatedAt")),
							jen.Qual(pkgTestifyAssert, "NotZero").Call(jen.Id("t"), jen.Id("got").Dot("UpdatedAt")),
						),
				),
			),
		),
	)
}

func (b *repositoryUnitTestBuilder) updateBody() jen.Code {
	return segments(
		jen.Comment("Create test data"),

		// create := &pb.ExampleCreate{}
		// created, err := repo.Create(ctx, create)
		// require.NoError(t ,err)
		// require.NotNil(t, created)
		define("create").Op("&").Qual(b.ProtoPackage, b.node.Name+"Create").Add(b.mockData()),
		define("created", "err").Id("repo").Dot("Create").Call(jen.Id("ctx"), jen.Id("create")),
		jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Id("err")),
		jen.Qual(pkgTestifyRequire, "NotNil").Call(jen.Id("t"), jen.Id("created")),

		jen.Line(),

		define("now").Qual(pkgTime, "Now").Call(),
		define("timestamp").Qual(pkgTimestamppb, "New").Call(jen.Id("now")),

		jen.Line(),

		// tests := []ExampleUpdateAssert{}
		define("tests").Op("[]").Id(fmt.Sprintf("%sUpdateAssert", b.node.Name)).Block(
			jen.Block(
				jen.Id("name").Op(":").Lit("update all fields").Op(","),
				jen.Id("id").Op(":").Id("created").Dot("ID").Op(","),
				jen.Id("update").Op(":").Op("&").Qual(b.ProtoPackage, b.node.Name+"Update").Add(b.mockData(true)).Op(","),
				jen.Id("wantError").Op(":").False().Op(","),
			).Op(","),
			jen.Block(
				jen.Id("name").Op(":").Lit("update with timestamps").Op(","),
				jen.Id("id").Op(":").Id("created").Dot("ID").Op(","),
				jen.Id("update").Op(":").Op("&").Qual(b.ProtoPackage, b.node.Name+"Update").Block(
					jen.Id("CreatedAt").Op(":").Id("timestamp").Op(","),
					jen.Id("UpdatedAt").Op(":").Id("timestamp").Op(","),
				).Op(","),
				jen.Id("wantError").Op(":").False().Op(","),
			).Op(","),
			jen.Block(
				jen.Id("name").Op(":").Lit("update no-existent record").Op(","),
				jen.Id("id").Op(":").Lit(99999).Op(","),
				jen.Id("update").Op(":").Op("&").Qual(b.ProtoPackage, b.node.Name+"Update").Add(b.mockData(true)).Op(","),
				jen.Id("wantError").Op(":").True().Op(","),
			).Op(","),
			jen.Block(
				jen.Id("name").Op(":").Lit("update with empty data").Op(","),
				jen.Id("id").Op(":").Id("created").Dot("ID").Op(","),
				jen.Id("update").Op(":").Op("&").Qual(b.ProtoPackage, b.node.Name+"Update").Block().Op(","),
				jen.Id("wantError").Op(":").False().Op(",").Comment("no error, no changes"),
			).Op(","),
		),

		// for _, tt := range tests {}
		jen.For(jen.Id("_").Op(",").Id("tt").Op(":=").Range().Id("tests")).Block(
			// t.Run(tt.name, func(t *testing.T)) {}
			jen.Id("t").Dot("Run").Call(
				jen.Id("tt").Dot("name"),
				jen.Func().Params(jen.Id("t").Op("*").Qual(pkgTesting, "T")).Block(
					define("err").Id("repo").Dot("Update").Call(jen.Id("ctx"), jen.Id("tt").Dot("id"), jen.Id("tt").Dot("update")),
					jen.If(jen.Id("tt").Dot("wantError")).
						Block(jen.Qual(pkgTestifyAssert, "Error").Call(jen.Id("t"), jen.Err())).
						Else().
						Block(
							jen.Qual(pkgTestifyAssert, "NoError").Call(jen.Id("t"), jen.Err()),
							jen.Comment("// Verify update if not expecting error and ID exists"),
							b.assertEqualUpdateFields(),
						),
				),
			),
		),
	)
}

func (b *repositoryUnitTestBuilder) listTestCases() jen.Code {
	codes := jen.Statement{}
	codes = append(
		codes,
		jen.Block(
			jen.Id("name").Op(":").Lit("list all without pagination").Op(","),
			jen.Id("options").Op(":").Op("&").Qual(b.ProtoPackage, b.node.Name+"Options").Block().Op(","),
			jen.Id("paginator").Op(":").Nil().Op(","),
			jen.Id("wantCount").Op(":").Lit(3).Op(","),
			jen.Id("wantError").Op(":").False().Op(","),
		).Op(","),
		jen.Block(
			jen.Id("name").Op(":").Lit("list with pagination").Op(","),
			jen.Id("options").Op(":").Op("&").Qual(b.ProtoPackage, b.node.Name+"Options").Block().Op(","),
			jen.Id("paginator").Op(":").Op("&").Qual(pkgCoconutField, "ClassicalPaginator").Block(jen.Id("Page").Op(":").Lit(1).Op(",").Id("Limit").Op(":").Lit(2).Op(",")).Op(","),
			jen.Id("wantCount").Op(":").Lit(2).Op(","),
			jen.Id("wantError").Op(":").False().Op(","),
		).Op(","),
		jen.Block(
			jen.Id("name").Op(":").Lit("list with pagination page 2").Op(","),
			jen.Id("options").Op(":").Op("&").Qual(b.ProtoPackage, b.node.Name+"Options").Block().Op(","),
			jen.Id("paginator").Op(":").Op("&").Qual(pkgCoconutField, "ClassicalPaginator").Block(jen.Id("Page").Op(":").Lit(2).Op(",").Id("Limit").Op(":").Lit(2).Op(",")).Op(","),
			jen.Id("wantCount").Op(":").Lit(1).Op(","),
			jen.Id("wantError").Op(":").False().Op(","),
		).Op(","),
	)
	return &codes
}

func (b *repositoryUnitTestBuilder) assertEqualGetFields() jen.Code {
	var fields []jen.Code
	for _, v := range b.node.Fields {
		if v.Optional || v.Name == "created_at" || v.Name == "updated_at" || v.Name == "deleted_at" {
			continue
		}
		fields = append(
			fields,
			jen.Qual(pkgTestifyAssert, "Equal").Call(
				jen.Id("t"),
				jen.Id("tt").Dot("want").Dot(text.EntPascal(v.Name)),
				jen.Id("got").Dot(text.EntPascal(v.Name)),
			),
		)
	}
	return segments(fields...)
}

func (b *repositoryUnitTestBuilder) assertEqualCreateFields() jen.Code {
	var fields []jen.Code
	for _, v := range b.node.Fields {
		if v.Optional || v.Name == "created_at" || v.Name == "updated_at" || v.Name == "deleted_at" {
			continue
		}
		fieldOpts, err := entproto.GetFieldOptions(v.Annotations)
		if err != nil {
			continue
		}
		fields = append(
			fields,
			jen.Qual(pkgTestifyAssert, "Equal").Call(
				jen.Id("t"),
				entType(v.Type.Type, jen.Id("tt").Dot("create").Dot(text.EntPascal(v.Name)), &fieldOpts),
				jen.Id("got").Dot(text.EntPascal(v.Name)),
			),
		)
	}
	return segments(fields...)
}

func (b *repositoryUnitTestBuilder) assertEqualUpdateFields() jen.Code {
	var fields []jen.Code
	for _, v := range b.node.Fields {
		if v.Optional || v.Name == "created_at" || v.Name == "updated_at" || v.Name == "deleted_at" {
			continue
		}
		fieldOpts, err := entproto.GetFieldOptions(v.Annotations)
		if err != nil {
			continue
		}
		seg := jen.If(jen.Id("tt").Dot("update").Dot(text.ProtoPascal(v.Name)).Op("!=").Nil()).Block(
			jen.Qual(pkgTestifyAssert, "Equal").Call(
				jen.Id("t"),
				entType(v.Type.Type, jen.Op("*").Id("tt").Dot("update").Dot(text.ProtoPascal(v.Name)), &fieldOpts),
				jen.Id("updated").Dot(text.EntPascal(v.Name)),
			),
		)
		fields = append(fields, seg)
	}
	return jen.If(jen.Op("!").Id("tt").Dot("wantError").Op("&&").Id("tt").Dot("id").Op("==").Id("created").Dot("ID")).Block(
		define("updated", "err").Id("repo").Dot("Get").Call(jen.Id("ctx"), jen.Id("tt").Dot("id")),
		jen.Qual(pkgTestifyRequire, "NoError").Call(jen.Id("t"), jen.Err()),
		segments(fields...),
	)
}

func (b *repositoryUnitTestBuilder) getAssertStruct() jen.Code {
	return jen.Type().Id(fmt.Sprintf("%sGetAssert", b.node.Name)).Struct(
		jen.Id("name").String(),
		jen.Id("id").Id(b.node.ID.Type.String()),
		jen.Id("want").Op("*").Qual(b.entityPackage, b.node.Name),
		jen.Id("wantError").Bool(),
	).Line()
}

func (b *repositoryUnitTestBuilder) listAssertStruct() jen.Code {
	return jen.Type().Id(fmt.Sprintf("%sListAssert", b.node.Name)).Struct(
		jen.Id("name").String(),
		jen.Id("options").Op("*").Qual(b.ProtoPackage, b.node.Name+"Options"),
		jen.Id("paginator").Op("*").Qual(pkgCoconutField, "ClassicalPaginator"), // TODO
		jen.Id("wantCount").Int(),
		jen.Id("wantError").Bool(),
	).Line()
}

func (b *repositoryUnitTestBuilder) createAssertStruct() jen.Code {
	return jen.Type().Id(fmt.Sprintf("%sCreateAssert", b.node.Name)).Struct(
		jen.Id("name").String(),
		jen.Id("create").Op("*").Qual(b.ProtoPackage, b.node.Name+"Create"),
		jen.Id("wantError").Bool(),
	).Line()
}

func (b *repositoryUnitTestBuilder) updateAssertStruct() jen.Code {
	return jen.Type().Id(fmt.Sprintf("%sUpdateAssert", b.node.Name)).Struct(
		jen.Id("name").String(),
		jen.Id("id").Id(b.node.ID.Type.String()),
		jen.Id("update").Op("*").Qual(b.ProtoPackage, b.node.Name+"Update"),
		jen.Id("wantError").Bool(),
	).Line()
}

func (b *repositoryUnitTestBuilder) deleteAssertStruct() jen.Code {
	return jen.Type().Id(fmt.Sprintf("%sDeleteAssert", b.node.Name)).Struct(
		jen.Id("name").String(),
		jen.Id("id").Id(b.node.ID.Type.String()),
		jen.Id("wantError").Bool(),
	).Line()
}
func (b *repositoryUnitTestBuilder) setAssertStruct() jen.Code {
	return jen.Type().Id(fmt.Sprintf("%sSetAssert", b.node.Name)).Index(jen.Id("T").Any()).Struct(
		jen.Id("name").String(),
		jen.Id("id").Id(b.node.ID.Type.String()),
		jen.Id("value").Id("T"),
		jen.Id("wantError").Bool(),
	).Line()
}

func (b *repositoryUnitTestBuilder) mockData(ptr ...bool) *jen.Statement {
	var fields []jen.Code
	for _, v := range b.node.Fields {
		if v.Optional || v.Name == "created_at" || v.Name == "updated_at" || v.Name == "deleted_at" {
			continue
		}
		fieldOpts, err := entproto.GetFieldOptions(v.Annotations)
		if err != nil {
			continue
		}
		val := b.mockValue(v, &fieldOpts)
		if len(ptr) > 0 && ptr[0] {
			val = jen.Id("pointer").Call(val)
		}
		fields = append(fields, jen.Id(text.ProtoPascal(v.Name)).Op(":").Add(val).Op(","))
	}
	return jen.Block(fields...)
}

func (b *repositoryUnitTestBuilder) mockValue(v *gen.Field, opts *entproto.FieldOptions) *jen.Statement {
	t := v.Type.Type
	if opts.Type > 0 {
		t = opts.Type
	}

	var val *jen.Statement
	switch t {
	case field.TypeBool:
		val = jen.True()
	case field.TypeTime:
		val = jen.Qual(pkgTime, "Now").Call()
	case field.TypeUUID:
		val = jen.Qual(pkgUUID, "New").Call()
	case field.TypeEnum:
		val = jen.Lit(v.EnumValues()[rand.Intn(len(v.EnumValues()))])
	case field.TypeString:
		val = RandString(fmt.Sprintf("test_%s_%s_", b.node.Name, v.Name), 8)
	case field.TypeBytes:
		val = RandBytes(8)
	case field.TypeInt8, field.TypeInt16, field.TypeInt32, field.TypeInt, field.TypeInt64, field.TypeUint8, field.TypeUint16, field.TypeUint32, field.TypeUint, field.TypeUint64, field.TypeFloat32, field.TypeFloat64:
		if opts.ProtoEnum {
			val = RandEnum(b.ProtoPackage, b.node, v, opts.ProtoEnumValue)
		} else {
			val = RandNumber(256)
		}
	default:
		val = &jen.Statement{}
	}
	return val
}
