// Code generated by Wire. DO NOT EDIT.
// @file: internal/bootstrap/wire_gen.go
//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap