// Code generated by coconutc. DO NOT EDIT.
// @file: internal/infra/data/error.go

package data

import (
	"fmt"
	"runtime"
)

type (
    ParameterNilError string
)

func (e ParameterNilError) Error() string {
	_, file, line, ok := runtime.Caller(6)
	if ok {
		return fmt.Sprintf("parameter %s cannot be nil, at %s:%d", string(e), file, line)
	}
	return fmt.Sprintf("parameter %s cannot be nil", string(e))
}

func pointer[T any](v T) *T {
	return &v
}