// Code generated by coconutc. DO NOT EDIT.
// @file: ent/enttest/client.go

package enttest

import (
    "entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"{{.Module}}/ent"
)

func MemoryClient(t TestingT) *ent.Client {
	drv, err := sql.Open(dialect.SQLite, "file:test?mode=memory&cache=shared&_pragma=foreign_keys=1")
	if err != nil {
		t.Error(err)
		t.FailNow()
	}
	return NewClient(
		t,
		WithOptions(ent.Driver(drv)),
		// WithMigrateOptions(migrate.WithForeignKeys(false)), // maybe you want to remove foreign keys constraint in test
	)
}
